src/MqTest/Controllers/TicketsController.cs
using Data.Models;
using Data.Services;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using MqTest.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace MqTest.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ITbTicketService _tbTicket;
        private readonly ITbAdjuntoTicketService _adjuntoTicket;
        private readonly ITbUsuarioService _tbUsuario;
        private readonly ITbTipoProbemaService _tipoProbema;

        public TicketsController()
        {
            var ctx = new MqContext();
            _tbTicket = new TbTicketService(ctx);
            _adjuntoTicket = new TbAdjuntoTicketService(ctx);
            _tbUsuario = new TbUsuarioService(ctx);
            _tipoProbema = new TbTipoProbemaService(ctx);
        }

        //
        // GET: /Tickets/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Solicitudes/
        public ActionResult Solicitudes()
        {
            PopulateTipoProblemas();
            PopulateEstado();
            return View();
        }

        public ActionResult SolicitudesB()
        {
            PopulateTipoProblemas();
            PopulateEstado();
            return View();
        }

        //
        // POST: /Tickets/Create
        [HttpPost]
        public ActionResult Create(TbTicket values)
        {
            try
            {
                values.CreadoEn = DateTime.Now;
                values.CreadoPor = Cuser.NombreUsuario;
                values.ModificadoEn = new DateTime(1971, 1, 1);
                values.ModificadoPor = "";
                values.IdDepartamento = GetDeptoUsuario(Convert.ToInt32(Cuser.Usuario));
                values.Estado = "A";
                _tbTicket.Insert(values);
                _tbTicket.Save();

                return Json(new { state = "ok" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return View("Error");
            }
        }

        //
        // GET: /Tickets/Edit/5
        public ActionResult Edit(int id)
        {
            var data = _tbTicket.GetById(id);
            return View(data);
        }

        //
        // POST: /Tickets/Edit/5
        [HttpPost]
        public ActionResult Edit(TbTicket values)
        {
            try
            {
                var data = _tbTicket.GetById(values.IdTicket);
                if (data != null)
                {
                    data.Descripcion = values.Descripcion.Trim();
                    data.Estado = values.Estado;
                    data.IdTipoProblema = values.IdTipoProblema;
                    data.Titulo = values.Titulo;
                    if (values.Estado == "C")
                    {
                        data.FechaCerrado = DateTime.Now;
                    }
                    data.ModificadoEn = DateTime.Now;
                    data.ModificadoPor = Cuser.NombreUsuario;

                    _tbTicket.Save();
                }

                return Json(new { state = "ok" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return View();
            }
        }

        public JsonResult GetUsuario(string text)
        {
            var data = _tbUsuario.GetAll();
            if (text.Length > 2)
            {
                data = data.Where(x => x.Nombre.ToLower().Contains(text.ToLower()) ||
                    x.NombreUsuario.ToLower().Contains(text.ToLower()));
            }
            var dataToSend = (from r in data
                              select new
                              {
                                  r.Nombre,
                                  Codigo = r.IdUsuario
                              }).ToList();
            return Json(dataToSend, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTipoProblemas(string text)
        {
            var data = _tipoProbema.GetAll();
            if (text.Length > 2)
            {
                data = data.Where(x => x.Descripcion.ToLower().Contains(text.ToLower()));
            }
            var dataToSend = (from r in data
                              select new
                              {
                                  Nombre = r.Descripcion,
                                  Codigo = r.IdTipoProblema
                              }).ToList();
            return Json(dataToSend, JsonRequestBehavior.AllowGet);
        }

        private void PopulateTipoProblemas()
        {
            var empleados = _tipoProbema.GetAll();
            var data = from r in empleados
                       select new
                       {
                           Text = r.Descripcion,
                           Value = r.IdTipoProblema
                       };
            ViewData["tipoProblemas"] = data;
        }

        private void PopulateEstado()
        {
            var perfilLst = new List<ListItem>
            {
                new ListItem { Text = "Abierto", Value="A" },
                new ListItem { Text = "Cerrado", Value="C" },
                new ListItem { Text = "Desestimado", Value="D" }
            };
            ViewData["estados"] = perfilLst;
        }

        private int GetDeptoUsuario(int idUsuario)
        {
            var data = _tbUsuario.GetById(idUsuario);
            return data.IdDepartamento;
        }

        public ActionResult GetMisSolcitudes([DataSourceRequest] DataSourceRequest request)
        {
            var data = _tbTicket.GetAll().Where(x => x.IdUsuarioSolicitante == Convert.ToInt32(Cuser.Usuario));
            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSolcitudes([DataSourceRequest] DataSourceRequest request)
        {
            var data = _tbTicket.GetAll();
            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveFile(IEnumerable<HttpPostedFileBase> files)
        {
            if (files == null) return Content("");
            foreach (var file in files)
            {
                var fileName = Path.GetFileName(file.FileName);
                if (fileName != null)
                {
                    var physicalPath = Path.Combine(Server.MapPath("~/Files"), fileName);
                    file.SaveAs(physicalPath);
                }
            }

            // Return an empty string to signify success
            return Content("");
        }

        public ActionResult RemoveFile(string[] fileNames)
        {
            if (fileNames != null)
            {
                foreach (var fullName in fileNames)
                {
                    var fileName = Path.GetFileName(fullName);
                    if (fileName != null)
                    {
                        var physicalPath = Path.Combine(Server.MapPath("~/App_Data"), fileName);

                        // TODO: Aquí se deben verificar los permisos de lectura y o escritura.

                        if (System.IO.File.Exists(physicalPath))
                        {
                            System.IO.File.Delete(physicalPath);
                        }
                    }
                }
            }

            // Return an empty string to signify success
            return Content("");
        }

        //
        // GET: /TipoCartas/Upload/5
        public ActionResult Upload(int id)
        {
            var data = new TbAdjuntoTicket { IdTicket = id };
            return View(data);
        }

        [HttpPost]
        public ActionResult Upload(TbAdjuntoTicket values)
        {
            try
            {
                values.CreadoEn = DateTime.Now;
                values.CreadoPor = Cuser.NombreUsuario;
                values.ModificadoEn = new DateTime(1971, 1, 1);
                values.ModificadoPor = "";

                _adjuntoTicket.Insert(values);
                _adjuntoTicket.Save();

                return Json(new { state = "ok" }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult GetAdjuntos([DataSourceRequest] DataSourceRequest request, int idTicket)
        {
            var data =
                _adjuntoTicket.GetAll()
                    .Where(x => x.IdTicket == idTicket);
            return Json(data.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public FileResult Download(string fileName)
        {
            var contentType = string.Empty;

            if (fileName.Contains(".pdf"))
            {
                contentType = "application/pdf";
            }
            else if (fileName.Contains(".docx"))
            {
                contentType = "application/docx";
            }
            return new FilePathResult("~/Files/" + fileName, contentType);
        }
    }
}

src/MqTest/Views/Tickets/Edit.cshtml
@model Data.Models.TbTicket

@{
    ViewBag.Title = "Editar Solicitud";
}

<div class="row">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><span class="glyphicon glyphicon-home"></span></a></li>
        <li class="active">Solcitudes</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Editar Solicitudes</h1>
    </div>
</div><!--/.row-->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Editar Solicitud
                <a href="@Url.Action("Solicitudes")" class="btn btn-primary btn-xs" style="float: right; margin-top: 14px;" id="btnConsultar"> <i class="glyphicon glyphicon-search"></i> Consultar Solicitudes</a>
            </div>
            <div class="panel-body">
                @using (Ajax.BeginForm("Edit", "Tickets", new AjaxOptions { HttpMethod = "POST", OnFailure = "onFailure", OnSuccess = "onSuccess", }, new { id = "frm" }))
                {
                    @Html.HiddenFor(x => x.IdTicket)
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">Registrado para: </label>
                            <div class="col-sm-4">
                                @(Html.Kendo().DropDownList()
                                      .Name("idUsuarioSolicitante")
                                      .DataTextField("Nombre")
                                      .DataValueField("Codigo")
                                      .Enable(false)
                                      .HtmlAttributes(new { style = "width:100%" })
                                      .Filter("contains")
                                      .DataSource(source =>
                                      {
                                          source.Read(read =>
                                          {
                                              read.Action("GetUsuario", "Tickets");
                                          })
                                              .ServerFiltering(true);
                                      })
                                )
                                @Html.ValidationMessageFor(x => x.IdUsuarioSolicitante)
                            </div>
                            <label class="col-sm-2 control-label no-padding-right">Problema: </label>
                            <div class="col-sm-4">
                                @(Html.Kendo().DropDownList()
                                      .Name("idTipoProblema")
                                      .DataTextField("Nombre")
                                      .DataValueField("Codigo")

                                      .HtmlAttributes(new { style = "width:100%" })
                                      .Filter("contains")
                                      .DataSource(source =>
                                      {
                                          source.Read(read =>
                                          {
                                              read.Action("GetTipoProblemas", "Tickets");
                                          })
                                              .ServerFiltering(true);
                                      })
                                )
                                @Html.ValidationMessageFor(x => x.IdTipoProblema)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">Título: </label>
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Titulo, new { @class = "form-control", maxlength = 75 })
                                @Html.ValidationMessageFor(x => x.Titulo)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">Descripción: </label>
                            <div class="col-sm-10">
                                @Html.TextAreaFor(x => x.Descripcion, new { @class = "form-control", maxlength = 200 })
                                @Html.ValidationMessageFor(x => x.Descripcion)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">Modificado Por: </label>
                            <div class="col-sm-4">
                                @Html.TextBoxFor(x => x.ModificadoPor, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                            <label class="col-sm-2 control-label no-padding-right">Modificado En: </label>
                            <div class="col-sm-4">

                                @Html.TextBoxFor(x => x.ModificadoEn, new { @class = "form-control", @readonly = "readonly" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">Estado: </label>
                            <div class="col-sm-4">
                                @(Html.Kendo().DropDownList()
                                      .Name("estado")
                                      .DataTextField("Text")
                                      .DataValueField("Value")
                                      .OptionLabel("Seleccione...")
                                      .BindTo(new List<SelectListItem>()
                                      {
                                          new SelectListItem()
                                          {
                                              Text = "Abierto",
                                              Value = "A"
                                          },
                                          new SelectListItem()
                                          {
                                              Text = "Cerrado",
                                              Value = "C"
                                          },
                                          new SelectListItem()
                                          {
                                              Text = "Desestimado",
                                              Value = "D"
                                          }
                                      })
                                      .HtmlAttributes(new { style = "width: 100%" })
                                )
                            </div>
                            <label class="col-sm-2 control-label no-padding-right">Archivos: </label>
                            <div class="col-sm-4">
                                <a href="javascript:void(0)" id="btnFile" class="btn btn-primary">Subir Archivo</a>
                            </div>
                        </div>
                        <div id="dvButton">
                            <button type="submit" onclick="" class="btn btn-primary">Guardar</button>
                            <a href="@Url.Action("Solicitudes")" class="btn btn-warning">Cancelar</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Archivos
            </div>
            <div class="panel-body">
                @(Html.Kendo().Grid<Data.Models.TbAdjuntoTicket>()
        .Name("grid")
        .Pageable()
        .Sortable()
        .Scrollable()
        .Filterable()
        .Columns(col =>
        {
            col.Bound(c => c.IdAdjunto).Title("Id").Width("10%");
            col.Bound(c => c.RutaAdjunto).Title("Archivo");
            col.Bound(c => c.Extension).Title("Extensión");
            col.Bound(c => c.CreadoEn).Title("Creado En").Format("{0:dd/MM/yyyy}");
            col.Template(@<text></text>).ClientTemplate("<a class='btn btn-primary btn-xs' href='" + Url.Action("Download", "Tickets") + "/?fileName=#=RutaAdjunto#'><i class='glyphicon glyphicon-download-alt'></i>Descargar</a>");
        })

            .DataSource(dataSource => dataSource
                .Ajax()
                        .Read(read => read.Action("GetAdjuntos", HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()).Data("getParameter"))
                )
                .Resizable(resize => resize.Columns(true))
                .Reorderable(reorder => reorder.Columns(true))
                )
            </div>
        </div>
    </div>
</div>
@*Modals*@
<div class="modal" tabindex="-1" id="nuevo">
    <div class="modal-dialog modal-lg" id="nuevo_content">

    </div>
</div>
<script type="text/javascript">
    var docRoot = '@Url.Content("~/")';
    $(document).ready(function () {
        $.validator.unobtrusive.parse($('#frm'));
        $('#btnFile').on('click', function () {
            var id = $("#IdTicket").val();
            $('#nuevo_content').html("");
            $('#nuevo_content').load(docRoot + '@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()/Upload/' + id);
            $('#nuevo').modal('show');
        });
    });
    var onFailure = function (result) {
        alert(result);
    }
    var onSuccess = function (result) {
        if (result["state"] != undefined && result["state"] === "ok") {
            alert("Datos actualizados");
            window.location.href = "/Tickets/Solicitudes";
        }

    };

    var onSuccessFile = function (result) {
        if (result["state"] != undefined && result["state"] === "ok") {
            alert("Archivo Cargado");
            BindGrid();
            $('#nuevo').modal('hide');
            $('#nuevo_content').html("");
        }

    };

    function onSelect(e) {
        console.log(e);
        $("#RutaAdjunto").val(getFileName(e));
    }
    function onUpload(e) {
        var files = e.files;

        $.each(files, function () {

            if (this.extension.toLowerCase() !== ".pdf") {
                alert("Solo se puede subir archivo con formato .rtf!");
                e.preventDefault();
            }

            if (this.size / 1024 / 1024 > 5) {
                alert("El archivo debe pesar menos de 5mb!");
                e.preventDefault();
            }
        });
    }
    function getFileName(e) {
        return $.map(e.files, function (file) {
            var info = file.name;
            return info;
        }).join(", ");
    }
    function getParameter() {
        return {
            idTicket: $("#IdTicket").val()
        };
    }
    function BindGrid() {
        $("#grid").data("kendoGrid").dataSource.read();
        $("#grid").data("kendoGrid").refresh();
    }
</script>

src/MqTest/Views/Tickets/Index.cshtml
@model Data.Models.TbTicket

@{
    ViewBag.Title = "Nueva Solicitud";
}

<div class="row">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index","Home")"><span class="glyphicon glyphicon-home"></span></a></li>
        <li class="active">Acciones</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Solicitud de Acciones</h1>
    </div>
</div><!--/.row-->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Nueva Acción
                <a href="@Url.Action("SolicitudesB")" class="btn btn-primary btn-xs" style="float: right; margin-top: 14px;" id="btnConsultar"> <i class="glyphicon glyphicon-search"></i> Consultar Solicitudes</a>
            </div>
            <div class="panel-body">
                @using (Ajax.BeginForm("Create", "Tickets", new AjaxOptions { HttpMethod = "POST", OnFailure = "onFailure", OnSuccess = "onSuccess", }, new { id = "frm" }))
                {
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">Registrado para: </label>
                            <div class="col-sm-4">
                                @(Html.Kendo().DropDownList()
                          .Name("idUsuarioSolicitante")
                                  .DataTextField("Nombre")
                                  .DataValueField("Codigo")

                                  .HtmlAttributes(new { style = "width:100%" })
                                  .Filter("contains")
                                  .DataSource(source =>
                                  {
                                      source.Read(read =>
                                      {
                                          read.Action("GetUsuario", "Tickets");
                                      })
                                          .ServerFiltering(true);
                                  })
                                )
                                @Html.ValidationMessageFor(x => x.IdUsuarioSolicitante)
                            </div>
                            <label class="col-sm-2 control-label no-padding-right">Problema: </label>
                            <div class="col-sm-4">
                                @(Html.Kendo().DropDownList()
                   .Name("idTipoProblema")
                                  .DataTextField("Nombre")
                                  .DataValueField("Codigo")

                                  .HtmlAttributes(new { style = "width:100%" })
                                  .Filter("contains")
                                  .DataSource(source =>
                                  {
                                      source.Read(read =>
                                      {
                                          read.Action("GetTipoProblemas", "Tickets");
                                      })
                                          .ServerFiltering(true);
                                  })
                                )
                                @Html.ValidationMessageFor(x => x.IdTipoProblema)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">Título: </label>
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Titulo, new { @class = "form-control", maxlength = 75 })
                                @Html.ValidationMessageFor(x => x.Titulo)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label no-padding-right">Descripción: </label>
                            <div class="col-sm-10">
                                @Html.TextAreaFor(x => x.Descripcion, new { @class = "form-control",maxlength=200 })
                                @Html.ValidationMessageFor(x => x.Descripcion)
                            </div>
                        </div>
                        <div id="dvButton">
                            <button type="submit" onclick="" class="btn btn-primary">Enviar</button>
                            <button type="reset" class="btn btn-warning">Limpiar</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $.validator.unobtrusive.parse($('#frm'));
    });
    var onFailure = function (result) {
        alert(result);
    }
    var onSuccess = function (result) {
        if (result["state"] != undefined && result["state"] === "ok") {
            alert("Solicitud eviada");
            window.location.reload();
            //document.getElementById("frm").reset();
        }

    };
</script>

src/MqTest/Views/Tickets/Solicitudes.cshtml
@model IEnumerable<Data.Models.TbTicket>
@{
    ViewBag.Title = "Consultar Solicitudes";
}

<div class="row">
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span></a></li>
        <li><a href="@Url.Action("Index","Tickets")"><span>Nueva Solicitud</span></a></li>
        <li class="active">Consultar Solicitudes</li>
    </ol>
</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Consultar Solicitudes</h1>
    </div>
</div><!--/.row-->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Solicitudes
            </div>
            <div class="panel-body">
                <div class="row">
                    @(
 Html.Kendo().Grid(Model)
        .Name("grid")
        .Pageable()
        .Sortable()
        .Scrollable()
        .Filterable()
        .Columns(col =>
        {
            col.Bound(c => c.IdTicket).Title("Id").Width("10%");
            col.Bound(c => c.Titulo).Title("Título");
            col.ForeignKey(c => c.IdTipoProblema, (System.Collections.IEnumerable)ViewData["tipoProblemas"], "Value", "Text").Title("Tipo Problema");
            col.ForeignKey(c => c.Estado, (System.Collections.IEnumerable)ViewData["estados"], "Value", "Text").Title("Estado");
            col.Bound(c => c.CreadoEn).Title("Creado En").Format("{0:dd/MM/yyyy}");
            col.Command(command => command.Custom("Editar").Click("fnEdit")).Width("99px");
        })

            .DataSource(dataSource => dataSource
                .Ajax()
                .Read(read => read.Action("GetSolcitudes", HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()))

                )
                .Resizable(resize => resize.Columns(true))
                .Reorderable(reorder => reorder.Columns(true))
                    )
                </div>
            </div>
        </div>
    </div><!-- /.col-->
</div><!-- /.row -->
@*Modales*@
<div class="modal" tabindex="-1" id="nuevo">
    <div class="modal-dialog modal-lg" id="nuevo_content">

    </div>
</div>

<div class="modal" tabindex="-1" id="editar">
    <div class="modal-dialog modal-lg" id="editar_content">

    </div>
</div>

<div class="modal" tabindex="-1" id="detalle">
    <div class="modal-dialog modal-lg" id="detalle_content">

    </div>
</div>

<script type="text/javascript">
    var docRoot = '@Url.Content("~/")';
    function fnEdit(e) {
        var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
        window.location.href = docRoot + '@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()/Edit/' + parseInt(dataItem.IdTicket);
    }

    function fnRechazr(id) {
        $.post(docRoot + '@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString()/Rechazar/', { Estado: "R", IdTicket: id })
            .done(function (data) {
                if (data["state"] != undefined && data["state"] === "ok") {
                    $('#grid').data('kendoGrid').dataSource.read();
                    $('#grid').data('kendoGrid').refresh();

                    $('#detalle').modal('hide');
                    $('#detalle_content').html("");
                    alert("Acción Rechazada...");
                }
                else {
                    alert("Ha ocurrido un error...");
                }
            });
    }
    var onFailure = function (result) {
        alert(result);
    }
    var onSuccess = function (result) {
        debugger;
        if (result["state"] != undefined && result["state"] === "ok") {
            $('#grid').data('kendoGrid').dataSource.read();
            $('#grid').data('kendoGrid').refresh();

            //
            $('#detalle').modal('hide');
            $('#detalle_content').html("");
        }
        //$.each(result, function(key, value) {
        //    if (value.length !== 0) {
        //        $("#" + key).next().append(value);
        //    }
        //});
    };
</script>