src/MqTest/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data.Models;
using Data.Services;
using MqTest.Models;

namespace MqTest.Controllers
{
    public class MenuController : Controller
    {
        private readonly ITbUsuarioService _usuario;

        public MenuController()
        {
            _usuario = new TbUsuarioService(new MqContext());
        }
        // GET: Navbar
        public ActionResult Navbar(string controller, string action)
        {
            var user = _usuario.GetAll().FirstOrDefault(x => x.NombreUsuario == Cuser.NombreUsuario);
            var perfil = user == null ? "0" : user.Perfil;
            var data = new Data.General.Options();
            var navBar = data.ItemsPerRoles(controller, action, perfil);
            return PartialView("_navbar", navBar);
        }
    }
}

src/MqTest/Views/Shared/_Layout.cshtml
@using MqTest.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - MQTEST</title>

    <link href="@Url.Content("~/Assets/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/Assets/css/styles.css")" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="~/Assets/js/html5shiv.min.js"></script>
    <script src="~/Assets/js/respond.min.js"></script>
    <![endif]-->
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/kendo/2015.2.902/kendo.common.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2015.2.902/kendo.mobile.all.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2015.2.902/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2015.2.902/kendo.silver.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/kendo/2015.2.902/kendo.dataviz.silver.min.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/kendo/2015.2.902/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2015.2.902/jszip.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2015.2.902/kendo.all.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2015.2.902/kendo.aspnetmvc.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")" title="MQ TEST"><span>MQ</span>TEST</a>
                <ul class="user-menu">
                    <li class="pull-right">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> @Cuser.Nombre</a>
                    </li>
                </ul>
            </div>

        </div><!-- /.container-fluid -->
    </nav>
    <!-- /Nav Top-->
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <form role="search">
            <div class="form-group">

            </div>
        </form>
        @Html.Action("Navbar", "Menu", new { controller = ViewContext.RouteData.Values["Controller"].ToString(), action = ViewContext.RouteData.Values["Action"].ToString() })
    </div><!--/.sidebar-->
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MQTEST.</p>
        </footer>
    </div>
  
    <script src="@Url.Content("~/Assets/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Assets/js/bootstrap-datepicker.js")"></script>
    <script>
        $('#calendar').datepicker({
        });
        var menuBoolean = !function ($) {
            $(document).on("click", "ul.nav li.parent > a > span.icon", function () {
                $(this).find('em:first').toggleClass("glyphicon-minus");
            });
            $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
        }(window.jQuery);
        $(window).on('resize', function () {
            if ($(window).width() > 768) $('#sidebar-collapse').collapse('show');
        });
        $(window).on('resize', function () {
            if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide');
        });
    </script>
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Assets/js/mqtest.js"></script>
</body>
</html>

src/MqTest/Views/Shared/_navbar.cshtml
@model IEnumerable<Data.Models.NavBar>
<ul class="nav menu">
    @foreach (var item in Model)
    {
        <li class="@item.Activeli">
            <a href="@Url.Action(item.Action, item.Controller)"><i class="@item.ImageClass"></i> @item.NameOption</a>
        </li>
    }
    <li role="presentation" class="divider"></li>
    <li><a href="@Url.Action("about","Home")"><span class="glyphicon glyphicon-info-sign"></span> Acerca de</a></li>
</ul>